const sources = ['ml/README.md', 'ml/PREPROCESSING.md', 'ml/POOLED_PREPROCESSING.md', 'scripts/README.md']

export function AboutModelPage() {
  return <section className="about-model-page">
    <header className="about-model-hero"><p className="eyebrow">Methodology</p><h2>How the model defines an out-braking attempt.</h2><p>This page reflects the project’s documented acquisition, preprocessing, and training decisions. It describes observational labels—not proof of driver intent or causation.</p></header>
    <div className="about-model-grid">
      <section className="about-model-card"><p className="eyebrow">01 · Data pulled</p><h3>Race context and telemetry</h3><p>For the all-driver workflow, the downloader collects completed Grands Prix and Sprints from 2023 onward. It discovers each session’s roster and keeps race-wide context alongside candidate-window telemetry.</p><ul><li>Positions, intervals, laps, stints, pit records, race control, weather, and overtakes.</li><li>Car data around candidate windows: brake, throttle, speed, gear, RPM, and DRS.</li><li>Location only after a credible attack signature or a confirmed pass, for braking position, distance, and corner clustering.</li></ul></section>
      <section className="about-model-card"><p className="eyebrow">02 · Attempt definition</p><h3>One row per distinct attempt</h3><p>Braking onset is a sustained brake transition from 0 to 1, preceded by at least one second without braking. Both drivers must enter the same braking event.</p><ul><li>The attacker must brake farther along the shared approach; the observed projected distance must be at least 5 m.</li><li>A success is a same-opponent pass within 10 seconds of braking onset.</li><li>Unconfirmed close following is excluded when it does not meet the stricter failure signature.</li></ul></section>
      <section className="about-model-card"><p className="eyebrow">03 · Quality controls</p><h3>Conservative exclusions</h3><p>The workflow excludes lapped traffic, pit-related windows, neutralized racing, missing telemetry, duplicate attempts, and ambiguous close following. Lap-one candidates are retained for audit but marked ineligible for default training.</p><ul><li>Both drivers must have a known equal lap number.</li><li>Pit-out laps and the preceding in-laps are excluded for either car.</li><li>Attempts are deduplicated within 20 seconds; braking separations above 100 m are rejected.</li></ul></section>
      <section className="about-model-card"><p className="eyebrow">04 · Model inputs</p><h3>Pre-attempt conditions</h3><p>The model-ready row includes gap, closing rate, attacker speed, speed delta, brake-onset delta, braking-distance delta, throttle-lift delta, tyre age and compound, DRS, rainfall, track temperature, and race progress.</p><p>Quality flags record missing braking distance, throttle lift, and weather before a final feature-completeness policy is selected.</p></section>
      <section className="about-model-card"><p className="eyebrow">05 · Logistic regression</p><h3>Pooled baseline</h3><p>The pooled baseline uses imputation, scaling, one-hot encoding, and class-balanced logistic regression. It tunes regularization with validation PR-AUC and selects its decision threshold using validation F1.</p><p>Evaluation reports ROC-AUC, average precision, and Brier score on an untouched test split. Transformations, coefficients, intercept, threshold, and evaluation metadata are exportable to browser-readable JSON.</p></section>
      <section className="about-model-card"><p className="eyebrow">06 · All-driver split</p><h3>Whole weekends stay together</h3><p>For pooled data, whole meeting keys are shuffled reproducibly within each year into approximately 70% training, 15% validation, and 15% testing. All drivers and both sessions from a weekend remain in one split.</p><p>The pooled trainer deliberately excludes driver identity so the initial model can generalize across the field. Sprint status remains audit metadata, not a prediction feature.</p></section>
    </div>
    <footer className="about-model-sources"><span>Documentation used</span><b>{sources.join(' · ')}</b></footer>
  </section>
}
